class AwsEnvironment:
    def __init__(self):
        self.description = "AWS Environment generated by CloudPrep"
        self.resources = []
        self.parameters = {}
        self.outputs = {}
        self.mappings = {}

        self._todo = []

    def findByPhysicalId(self, needle):
        for r in self.resources:
            if r.getPhysicalId() == needle:
                return r

        return None
